### ISSUE TITLE
Tailwindcss error with navbar

### ISSUE THREAD

**Issue by EzpieCo** [EzpieCo/ezpie#77]
I am kind of not good with tailwind and I just came across this error where the hamburger manu will just won't work

![issue](https://user-images.githubusercontent.com/104765117/230611898-f5e726d2-d352-42b6-9db4-c6a2719ad4bb.png)

On clicking the hamburger menu the navbar should expand and show the navbar links like any other navbar whould, but for some reason it just won't do that I tried a bunch of tricks but they just won't work.

If anyone knows how to solve it would be a plasure if you help out.

**Comment by mu-irfan** [comment]
@EzpieCo will fix this, assign me.

**Comment by EzpieCo** [comment]
Hi @mu-irfan sorry for the late response, this issue is all your take your time and don't worry if you can't sovle it. Ezpie is all about tring 😄

**Comment by andemosa** [comment]
@EzpieCo perhaps I can help out with fixing this issue

**Comment by EzpieCo** [comment]
Hi @andemosa. Yes you can help with this issue if you like. Take all the time you need 😄

**Comment by andemosa** [comment]
@EzpieCo  Awesome, I have worked on it and created a PR for it.
