### ISSUE TITLE
Typos in About Us

### ISSUE THREAD

**Issue by akebu6** [EzpieCo/ezpie#78]
The About Us Page on the site has typos that made it hard to understand what the all essence of the project is. I can work on fixing it

<img width="945" alt="Screenshot 2023-04-18 at 9 34 51 PM" src="https://user-images.githubusercontent.com/74776297/232886205-60b8c9f7-0fb5-4bd6-bfaa-d990e2cee3ef.png">

**Comment by EzpieCo** [comment]
Hi @akebu6 I am so sorry for such a late responce 😢 . Ya you can fix it if you like 😄

**Comment by akebu6** [comment]
Awesome, I shall have the changes made and uploaded by earlier tomorrow since it's already late here
